# syntax=docker/dockerfile:1
# Multi-stage image generated by CEF. The container installs and builds with npm for
# portability; the project's preferred package manager is recorded in .cef/project.json.
FROM node:20-alpine AS base
WORKDIR /app

FROM base AS deps
COPY package.json ./
RUN npm install

# Local development only — targeted by docker-compose.dev.yml. It costs the production image
# nothing: Docker builds a stage only when the target depends on it, and "runtime" does not.
FROM base AS dev
ENV NODE_ENV=development
ENV PORT=3000
COPY --from=deps /app/node_modules ./node_modules
COPY . .
EXPOSE 3000
CMD ["npm", "run", "dev"]

FROM base AS build
ENV NODE_ENV=production
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM base AS runtime
ENV NODE_ENV=production
ENV PORT=80
COPY --from=build /app ./
EXPOSE 80
CMD ["npm", "run", "start"]
