import js from '@eslint/js';
import tseslint from 'typescript-eslint';

// Project ESLint config generated by CEF. Extend as the app grows.
export default tseslint.config(
  { ignores: ['dist/**', '.next/**', 'build/**', 'node_modules/**', 'coverage/**'] },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['**/*.{ts,tsx}'],
    // TypeScript resolves every identifier itself; ESLint's version only produces false
    // positives on DOM and Node globals.
    rules: { 'no-undef': 'off' },
  },
);
